### ISSUE TITLE
Add support for JMS Serializer groups in views

### ISSUE THREAD

**Issue by Fabex** [stanlemon/rest-bundle#29]
Hi,
First your bundle is awesome :).
But I have a question, how I can use JMS Serializer groups ?
I defined some groups like "list" and "details" :
  - list is for api/entity
  - details for api/entity/{id}

For the list group I don't want all the properties of relation, just the id,  i.e for a user entity:

```json
[{
    "id": 1,
    "lastname": "Do",
    "firstname": "John",
    "group": 42
},{
    "id": 2,
    "lastname": "Son",
    "firstname": "Thom",
    "group": 21
}]
```
And for the details group I want all the properties of relation,  i.e for a user entity:
```json
{
    "id": 1,
    "lastname": "Do",
    "firstname": "John",
    "group":  {
        "id": 42,
        "name": "anonymous"
    }
}
```
I tried to use "lemon_rest.event_subscriber" by creating my subscriber, but I feel I can't access to the serializer
Or may be I can try with the "kernel.response" event but it feel to overkill.

I hope my question is clear. I wait your answer

**Comment by stanlemon** [comment]
@Fabex Right now there isn't really a way to filter by a group, though there definitely should be. I think the best way of tackling this would be to tie the serializer context object into the event system. This isn't currently done though, so I am going to mark this issue as a feature and I will address it in the future as soon as I am able.  With regards to just exposing the id's, check out the IdCollection serializer type that's included in the bundle. Using this type you can achieve what you're after. Thanks!

**Comment by Fabex** [comment]
@stanlemon thank you for your answer.
I will try to use IdCollection serializer type. And if I have time I will submit a PR to inject serializer context to the event system.

**Comment by stanlemon** [comment]
@Fabex I've been looking at this a little more and I was thinking about defining specific groups, such as ```lemon_rest.get``` and ```lemon_rest.list``` for example, and then set the serializer's context to ```$context->setGroups(array('Default', 'lemon_rest.list'));```.  Each request type would get it's own view. I'm wondering what you would think about this?

**Comment by Fabex** [comment]
@stanlemon yes it's was what I'm thinking but I will prefer that the dev choose these own groups. But for a first evol it will be perfect I think.

**Comment by patryyyck** [comment]
@stanlemon, i'm also interested in this evolution.  Using the request type (lemon_rest_list, lemon_rest_get) is a very good idea.

**Comment by stanlemon** [comment]
The develop branch includes my first pass at serializer groups. I am trying this out in a production application and if it shakes out I'll update the docs and add some more specific tests.

There are a series of views that can be applied:
- lemon_rest
- lemon_rest_$resource$
- lemon_rest_$resource$_$method$
- lemon_rest_$resource$_view
- lemon_rest_$resource$_list

$resource$ corresponds to the name you designate for the resource, the one that is used in your URLs.  If you don't specific an explicit name it's a plural form of the short class name.

$method$ is the http method used for the request.

The $resource$_view group should be used anytime a single object is rendered.

The $resource$_list group should be used anytime a collection of objects is rendered.

Again, I'm just beginning to test this so if you have the opportunity to try it out let me know. As I mentioned I am using it in an application right now.

Lastly, the develop branch also includes custom repositories, so be forewarned there may also be side affects from that if you choose to test this out.

Thanks everyone for your feedback on this feature!

**Comment by stanlemon** [comment]
This should now be handled in master.
