### ISSUE TITLE
The format "" is not supported for serialization

### ISSUE THREAD

**Issue by Gambit94** [stanlemon/rest-bundle#34]
Hi,
When I try to do a get or a post call I get this error:

"The format "" is not supported for serialization"
I have tried with a simple object with only id and name fields.

I haven't found any related issues/fix

**Comment by stanlemon** [comment]
Can you show me the request you're putting in?  Often times this will happen if the wrong Content-Type has been passed in.

**Comment by Gambit94** [comment]
![post](https://cloud.githubusercontent.com/assets/7414060/7088726/7f6c42fc-df96-11e4-8aaa-5261246b3fcb.PNG)
I am doing my test with chrome plugin POSTMAN, the issue is similar with a GET

**Comment by Gambit94** [comment]
Have I to set some headers ?

**Comment by stanlemon** [comment]
I've never used POSTMAN, this is what I do with curl:

```
curl -v -H "Accept: application/json" -d '{"foo": "bar"}' http://localhost/api/baz
```

And...

```
curl -v -H "Accept: application/json" http://localhost/api/baz/1
```

**Comment by Gambit94** [comment]
OK it works perfectly on normal call I close the issue

**Comment by stanlemon** [comment]
Awesome, thanks!

**Comment by Gambit94** [comment]
FYI It works fine on Postman with Accept: application/json header same with your curl
Thanks for your reactivity
