### ISSUE TITLE
Response Content-Type is text/html instead of application/json by default

### ISSUE THREAD

**Issue by GromNaN** [stanlemon/rest-bundle#40]
When I make a GET request in the browser without specifying the `Accept` header. The default response format is `html`. The [`Handler` changes it to `json`](https://github.com/stanlemon/rest-bundle/blob/master/Request/Handler.php#L80-L82).

The issue is that in the response, the `Content-Type` stays `text/html` whereas it should be `application/json`.

**Comment by stanlemon** [comment]
@GromNaN This was added originally to prevent a straight browser hit from causing a 500, as JMS does not have a HTML serializer.

**Comment by stanlemon** [comment]
Closing this as this is intentional behavior until someone crafts an HTML serializer for JMS.
