### ISSUE TITLE
"jms_serializer.json_serialization_visitor.options" not found

### ISSUE THREAD

**Issue by svengraziani** [stanlemon/rest-bundle#48]
Hi, i´ve just followed the Install instructions and after runing symfony it throw the following exception

ParameterNotFoundException in ParameterBag.php line 106:
You have requested a non-existent parameter "jms_serializer.json_serialization_visitor.options".

**Comment by svengraziani** [comment]
Alright, fixed the problem by adding the  new JMS\SerializerBundle\JMSSerializerBundle(), by hand at AppKernel .
Didnt see this step in the Getting Started.

**Comment by stanlemon** [comment]
@svengraziani Awesome, glad that wasn't a bug. I wish there was an easy way to load dependent bundles. Long term I think I will probably try to wire up the serializer directly in my bundle, but I haven't gotten there yet.  Anyhow, thanks for using the bundle!

**Comment by svengraziani** [comment]
i want to contribute an in-depth step by step getting started tutorial for your bundle, to show up common pitfalls one can run into.
